# Generated by Django 5.0.1 on 2024-02-01 12:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brandsitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Name')),
                ('img1', models.ImageField(upload_to='brands', verbose_name='Image 820 * 450')),
                ('des1', ckeditor.fields.RichTextField()),
                ('quote', ckeditor.fields.RichTextField()),
                ('des2', ckeditor.fields.RichTextField()),
                ('img2', models.ImageField(upload_to='brands', verbose_name='Image 545 * 505')),
                ('benefits', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
