# Generated by Django 5.0.1 on 2024-02-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brandsitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandsitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
