# Generated by Django 5.0.1 on 2024-02-05 16:55

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_alter_brandsitem_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='brandcontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('email', models.CharField(max_length=250, verbose_name='Email')),
                ('phono', models.CharField(max_length=250, verbose_name='Phone Number')),
                ('msg', ckeditor.fields.RichTextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brandsitem', verbose_name='Product/Brand name')),
            ],
        ),
    ]
