# Generated by Django 5.0.1 on 2024-02-05 19:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_alter_brandfaq_answer_alter_brandfaq_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandcontact',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
