# Generated by Django 5.0.1 on 2024-02-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.ImageField(default=1, upload_to='product', verbose_name='Image 2580 * 1200'),
            preserve_default=False,
        ),
    ]
