# Generated by Django 5.0.1 on 2024-02-01 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_products_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='productitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('img', models.CharField(max_length=50, verbose_name='Imgage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.products', verbose_name='Product')),
            ],
        ),
    ]
