# Generated by Django 5.0.1 on 2024-02-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='img',
            field=models.ImageField(upload_to='product/item', verbose_name='Image'),
        ),
    ]
