# Generated by Django 5.0.1 on 2024-02-01 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_alter_brandsitem_slug'),
        ('product', '0005_alter_productitem_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='name',
        ),
        migrations.AddField(
            model_name='productitem',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brands.brandsitem', verbose_name='Brand'),
            preserve_default=False,
        ),
    ]
