# Generated by Django 5.0.1 on 2024-02-05 16:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('email', models.CharField(max_length=250, verbose_name='Email')),
                ('phono', models.CharField(max_length=250, verbose_name='Phone Number')),
                ('msg', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
