# Generated by Django 5.0.1 on 2024-02-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Image 400 * 481'),
        ),
    ]
